[debian_vms]
debian1 ansible_host=192.168.56.101
debian2 ansible_host=192.168.56.102
debian3 ansible_host=192.168.56.103
debian5 ansible_host=192.168.56.108

[debian_vms:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_user=user
