machines = [
  { name: "test1", ip: "192.168.56.181", memory: 2048, cpus: 2 },
  { name: "test2", ip: "192.168.56.182", memory: 2048, cpus: 2 }
]

Vagrant.configure("2") do |config|

  machines.each do |m|
    config.vm.define m[:name] do |node|
      node.vm.box      = "debian/bookworm64"
      node.vm.hostname = m[:name]

      node.vm.network "private_network", ip: m[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.name   = m[:name]
        vb.memory = m[:memory]
        vb.cpus   = m[:cpus]
      end

      if Vagrant.has_plugin?("vagrant-vbguest")
        node.vbguest.auto_update = false
      end
    end
  end
end